// timds MCP server (SOURCE). It is bundled by scripts/build-mcp.mjs into
// mcp/timds-mcp.mjs (self-contained, with the shebang added by esbuild).
// To run the source in dev: `npm run mcp`.
// Exposes the design system (components, props/variants,
// tokens and page examples) as tools for code agents (Claude
// Code, Cursor, etc.), avoiding hallucinated props/imports.
//
// Data source: ai/manifest.json (generated by scripts/generate-ai-docs.mjs).
// Transport: stdio. Usage: `node mcp/timds-mcp.mjs` or via `claude mcp add`.

import { readFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'
import { McpServer } from '@modelcontextprotocol/sdk/server/mcp.js'
import { StdioServerTransport } from '@modelcontextprotocol/sdk/server/stdio.js'
import { z } from 'zod'

const __dirname = dirname(fileURLToPath(import.meta.url))
const manifestPath =
  process.env.TIMDS_MANIFEST || join(__dirname, '..', 'ai', 'manifest.json')

let manifest
try {
  manifest = JSON.parse(readFileSync(manifestPath, 'utf8'))
} catch (err) {
  console.error(
    `[timds-mcp] could not read the manifest at ${manifestPath}. ` +
      `Run \`npm run ai:docs\` in the timds lib. (${err.message})`,
  )
  process.exit(1)
}

const text = (s) => ({ content: [{ type: 'text', text: s }] })
const norm = (s) => s.toLowerCase().replace(/[\s_-]/g, '')

function findComponent(query) {
  const q = norm(query)
  return (
    manifest.components.find((c) => norm(c.name) === q || norm(c.module) === q) ||
    manifest.components.find((c) => c.exports.some((e) => norm(e) === q)) ||
    manifest.components.find(
      (c) => norm(c.name).includes(q) || norm(c.module).includes(q),
    )
  )
}

function formatComponent(c) {
  let out = `# ${c.name} (${c.status}) — category: ${c.category}\n\n`
  if (c.description) out += `${c.description}\n\n`
  out += `## Import\n\`\`\`tsx\n${c.importStatement}\n\`\`\`\n\n`
  out += `## Exports\n${c.exports.map((e) => `- \`${e}\``).join('\n')}\n`
  if (c.typeExports?.length) {
    out += `${c.typeExports.map((e) => `- \`${e}\` (type)`).join('\n')}\n`
  }
  out += '\n'
  const vk = Object.keys(c.variants || {})
  if (vk.length) {
    out += `## Variants\n`
    for (const k of vk) {
      out += `- \`${k}\`: ${c.variants[k].map((v) => `\`${v}\``).join(', ')}\n`
    }
    out += '\n'
  }
  const props = (c.props || []).filter((p) => p.description)
  if (props.length) {
    out += `## Props\n`
    for (const p of props) {
      const def = p.default ? ` _(default: \`${p.default}\`)_` : ''
      out += `- \`${p.name}\`${def} — ${p.description}\n`
    }
    out += '\n'
  }
  if (c.example) out += `## Example\n\`\`\`tsx\n${c.example}\n\`\`\`\n`
  return out
}

const server = new McpServer({ name: 'timds', version: manifest.version || '0.0.0' })

server.registerTool(
  'list_components',
  {
    title: 'List timds components',
    description:
      'Lists all components of the timds design system, grouped by category, ' +
      'with the short description and the exported symbols. Use it to discover what exists ' +
      'before building a screen.',
    inputSchema: {
      category: z
        .string()
        .optional()
        .describe('Filter by category (e.g.: "Data Display", "Layout").'),
    },
  },
  async ({ category }) => {
    let list = manifest.components
    if (category) {
      const q = norm(category)
      list = list.filter((c) => norm(c.category) === q || norm(c.category).includes(q))
    }
    const byCat = {}
    for (const c of list) {
      byCat[c.category] = byCat[c.category] || []
      byCat[c.category].push(c)
    }
    let out = `# timds — ${list.length} components\n\nCategories: ${manifest.categories.join(', ')}\n\n`
    for (const cat of Object.keys(byCat).sort()) {
      out += `## ${cat}\n`
      for (const c of byCat[cat]) {
        const d = c.description
          ? ` — ${c.description.split('. ')[0].replace(/\.$/, '')}`
          : ''
        out += `- **${c.name}** (\`${c.exports.join(', ')}\`)${d}\n`
      }
      out += '\n'
    }
    return text(out)
  },
)

server.registerTool(
  'get_component',
  {
    title: 'Get a timds component',
    description:
      'Complete details of a timds component: import, exports, variants, documented ' +
      'props and a code example. Accepts the component name or any ' +
      'export (e.g.: "Button", "card", "AvatarFallback").',
    inputSchema: {
      name: z.string().describe('Component name or an export name.'),
    },
  },
  async ({ name }) => {
    const c = findComponent(name)
    if (!c) {
      return text(
        `Component "${name}" not found. Use \`list_components\` to see the available ones.`,
      )
    }
    return text(formatComponent(c))
  },
)

server.registerTool(
  'search_components',
  {
    title: 'Search timds components',
    description:
      'Searches components by keyword in the name, description, category and exports. ' +
      'Use it when you do not know the exact name (e.g.: "modal", "dropdown", "chart").',
    inputSchema: {
      query: z.string().describe('Search term.'),
    },
  },
  async ({ query }) => {
    const q = norm(query)
    const hits = manifest.components.filter((c) => {
      const hay = norm(
        [c.name, c.module, c.category, c.description || '', c.exports.join(' ')].join(
          ' ',
        ),
      )
      return hay.includes(q)
    })
    if (!hits.length) return text(`No component found for "${query}".`)
    let out = `# Results for "${query}" (${hits.length})\n\n`
    for (const c of hits) {
      const d = c.description
        ? ` — ${c.description.split('. ')[0].replace(/\.$/, '')}`
        : ''
      out += `- **${c.name}** (\`${c.exports.join(', ')}\`)${d}\n`
    }
    return text(out)
  },
)

server.registerTool(
  'get_tokens',
  {
    title: 'Get timds design tokens',
    description:
      'timds design tokens: semantic color utilities (they resolve light/dark ' +
      'automatically), radius and font, plus the usage rules. Use it to style without ' +
      'raw colors.',
    inputSchema: {},
  },
  async () => {
    const t = manifest.tokens
    let out = `# timds design tokens\n\nRadius: \`${t.radius}\` · Font: \`${t.fontSans}\`\n\n`
    out += `## Rules\n${manifest.setup.rules.map((r) => `- ${r}`).join('\n')}\n\n`
    out += `## Colors (use as \`bg-*\`, \`text-*\`, \`border-*\`)\n`
    out += `| token | light | dark |\n|---|---|---|\n`
    for (const c of t.colors)
      out += `| \`${c.name}\` | ${c.light ?? '—'} | ${c.dark ?? '—'} |\n`
    return text(out)
  },
)

server.registerTool(
  'get_setup',
  {
    title: 'Get timds setup instructions',
    description:
      'How to install timds, import the styles and enable dark mode in a new project. ' +
      'Call this first when starting a project from scratch with timds.',
    inputSchema: {},
  },
  async () => {
    const s = manifest.setup
    let out = `# timds setup\n\n`
    out += `1. Install:\n\`\`\`bash\n${s.install}\n\`\`\`\n`
    out += `2. Import the styles in the entrypoint (JS, e.g.: main.tsx):\n\`\`\`tsx\n${s.importStyles}\n\`\`\`\n`
    out += `3. Import components:\n\`\`\`tsx\n${s.importComponents}\n\`\`\`\n`
    if (s.font) out += `   - Font: ${s.font}\n`
    if (s.charts) out += `   - Charts: ${s.charts}\n`
    if (s.tailwindBridge) {
      out += `4. (Tailwind v4 in the app) To use token utilities in your markup, add to your global CSS:\n\`\`\`css\n${s.tailwindBridge}\n\`\`\`\n`
    }
    out += `5. Dark mode: ${s.darkMode}\n\n`
    out += `## Rules\n${s.rules.map((r) => `- ${r}`).join('\n')}\n`
    return text(out)
  },
)

server.registerTool(
  'list_examples',
  {
    title: 'List timds page examples',
    description:
      'Lists the complete page compositions of timds (login, dashboard, settings, ' +
      'etc.) that serve as recipes. Use get_example for the code of one of them.',
    inputSchema: {},
  },
  async () => {
    let out = `# timds page examples\n\n`
    for (const e of manifest.examples) {
      out += `- **${e.id}** (${e.name})${e.description ? ` — ${e.description}` : ''}\n`
    }
    return text(out)
  },
)

server.registerTool(
  'get_example',
  {
    title: 'Get a timds page example',
    description:
      'Returns the complete source code of a timds page composition (e.g.: ' +
      '"dashboard", "login"), ready to adapt. Use list_examples to see the ids.',
    inputSchema: {
      id: z.string().describe('Example id (e.g.: "dashboard").'),
    },
  },
  async ({ id }) => {
    const q = norm(id)
    const e =
      manifest.examples.find((x) => norm(x.id) === q || norm(x.name) === q) ||
      manifest.examples.find((x) => norm(x.id).includes(q))
    if (!e) {
      return text(`Example "${id}" not found. Use \`list_examples\` to see the ids.`)
    }
    let out = `# Example: ${e.name}\n\n`
    if (e.description) out += `${e.description}\n\n`
    out += `> Import the components from \`timds\` (in the example they come from \`@/components/ui/*\` since it is internal to the lib).\n\n`
    out += `\`\`\`tsx\n${e.source}\n\`\`\`\n`
    return text(out)
  },
)

const transport = new StdioServerTransport()
await server.connect(transport)
console.error('[timds-mcp] server ready (stdio).')
